unified-delay: true
tcp-concurrent: true
geo-auto-update: true
geox-url:
  mmdb: https://glash.oss-cn-hangzhou.aliyuncs.com/Country.mmdb
dns:
  ipv6: true
  enable: true
  nameserver: [223.5.5.5, 223.6.6.6]
proxy-groups:
- {name: Proxy, type: select, proxies: [], use: [Subscription]}
proxies: null
rules:
- RULE-SET,AdBlock,REJECT
- RULE-SET,Global,Proxy
- RULE-SET,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Proxy
anchors:
  ipcidr: &ipcidr {type: http, interval: 36000, behavior: ipcidr, format: text}
  domain: &domain {type: http, interval: 36000, behavior: domain, format: text}
  classical: &classical {type: http, interval: 36000, behavior: classical, format: text}
  pp: &pp {type: http, interval: 36000, health-check: {enable: true, interval: 600, url: http://1.1.1.1/generate_204}}
proxy-providers:
  Subscription:
    <<: *pp
    url: "订阅链接"
    path: ./proxies/subscription.yaml
rule-providers:
  AdBlock:
    <<: *classical
    url: https://github.com/AkinoYuiko/surge-list/raw/main/AdBlock.list
  Global:
    <<: *classical
    url: https://github.com/AkinoYuiko/surge-list/raw/main/Global.list
  LAN:
    <<: *classical
    url: https://github.com/AkinoYuiko/surge-list/raw/main/LAN.list
